name: Trigger auto deployment for container-app-shj6chg57orjk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-shj6chg57orjk-AutoDeployTrigger-ea79d619-1886-4bb8-bc4c-afe606f0f2bb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSHJ6CHG57ORJK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSHJ6CHG57ORJK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSHJ6CHG57ORJK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPSHJ6CHG57ORJK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSHJ6CHG57ORJK_REGISTRY_PASSWORD }}
          containerAppName: container-app-shj6chg57orjk
          resourceGroup: fastifysample90109caf
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


